### PR TITLE
Apply Access Transforms to forks

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Resolves https://github.com/PaperMC/paperweight-examples/issues/4

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
Rebased on top of 1.1.15-SNAPSHOT

**Comment by yannicklamprecht** [comment]
Would be neat to have that officially support.

**Comment by TheShermanTanker** [comment]
> Would be neat to have that officially support.

Last I heard the main issue was that the process requires certain jars on the classpath, and it's not clear which ones can be omitted without any adverse effects on the access transformer. This isn't high on my to-do list at the moment, but I can start work on this again and rebase it on a recent paperweight version in my spare time

**Comment by yannicklamprecht** [comment]
> > Would be neat to have that officially support.
> 
> Last I heard the main issue was that the process requires certain jars on the classpath, and it's not clear which ones can be omitted without any adverse effects on the access transformer. This isn't high on my to-do list at the moment, but I can start work on this again and rebase it on a recent paperweight version in my spare time
> 
> (On a side note, it would be awesome if the solution included sending the output of the downloadSpigotDependencies task to paperweight-patcher; My fork desperately needs it right now :P)

Take your time, until then I'll just "manually" transform it by using patches or try updating it myself when I need it more urgently.

**Comment by TheShermanTanker** [comment]
Closed - Too many merge conflicts, an incremental approach is being taken to achieve this instead

**Pull request closed without merging**
