### PR TITLE
Lock server dir for mc dev sources and apply patches

### PR DESCRIPTION
**Pull request by jpenilla**
Fixes IntelliJ deciding to sync during apply patches breaking git state

### CODE REVIEW

**Comment by jpenilla** [comment]
Needs Java 9 at runtime for ProcessHandle API, pre J9 it's a lot more difficult to handle this across platforms

**Comment by Machine-Maker** [comment]
So far this has fixed the issue on macos, probably someone should test on windows.

**Comment by jpenilla** [comment]
Tested on windows, should be good to merge provided we're fine with bumping to J11 runtime

**Comment by MiniDigger** [comment]
If we bump (and I don't see why we wouldn't), might as well bump to 17 since anybody using this new version uses a mc version that requires 17 anyways

**Pull request merged**
