### PR TITLE
Initial attempt at adding support for Reobf Mappings Patch for forks

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Currently forks of Paper do not have access to the patchReobfMappings task, and when reobfJar is executed on the project the resulting reobfuscation is incomplete. This patch attempts to fix that, but uses a hardcoded path for the reobf-mappings-patch for now due to odd projects errors encountered in creating this PR

### CODE REVIEW

**Comment by jpenilla** [comment]
This is not the correct approach, doing this properly would require something along the lines of merging upstream mappings patches and passing the merged patch downstream. (Unless the goal is simply to apply Paper's patch and not actually supporting forks making their own patches)

Hardcoding paths is an acceptable workaround for forks themselves to implement (see https://github.com/Tuinity/Tuinity/blob/8e7cc4dc969bf044ab472342538d519a824f358c/patches/server/0062-Apply-paper-s-reobf-mappings-patch.patch), however I don't think it's something we would want in paperweight itself.

**Comment by TheShermanTanker** [comment]
> 
> 
> This is not the correct approach, doing this properly would require something along the lines of merging upstream mappings patches and passing the merged patch downstream. (Unless the goal is simply to apply Paper's patch and not actually supporting forks making their own patches)
> 
> Hardcoding paths is an acceptable workaround for forks themselves to implement (see https://github.com/Tuinity/Tuinity/blob/8e7cc4dc969bf044ab472342538d519a824f358c/patches/server/0062-Apply-paper-s-reobf-mappings-patch.patch), however I don't think it's something we would want in paperweight itself.

The goal was only to apply the reobfuscation patch that Paper has currently, to result in a complete set of reobfuscation mappings for forks, as right now only the unpatched and incomplete reobf mappings are used when reobfJar is called. I don't think forks applying their custom reobfuscation patches would benefit them at all; If custom mappings patches are planned, it would make much more sense to have custom patch support for the original set of deobfuscation mappings that converts the Spigot source to Mojang names, rather than the reobfuscation mappings that convert Mojang names back to Spigot's runtime names (Though reobfJar functionality may have to disabled if that was the case?)

Currently I only hardcoded the path as a placeholder; I am not very well versed with Kotlin and didn't know where to place a constant containing the path

**Comment by jpenilla** [comment]
> I don't think forks applying their custom reobfuscation patches would benefit them at all;

Why not? A fork is just as capable of changing a `HashMap` to a `Reference2IntOpenHashMap`, for example, as Paper is, and when making such a change it shouldn't be surprising if they would like to fix reobf.

> Currently I only hardcoded the path as a placeholder; I am not very well versed with Kotlin and didn't know where to place a constant containing the path (Or if any of the pre-existing constants would work)

Using a constant containing the hardcoded path is still hardcoding the path. The location of the patch file would need to be passed through the upstream data.

**Comment by TheShermanTanker** [comment]
> 
> 
> > I don't think forks applying their custom reobfuscation patches would benefit them at all;
> 
> Why not? A fork is just as capable of changing a `HashMap` to a `Reference2IntOpenHashMap`, for example, as Paper is, and when making such a change it shouldn't be surprising if they would like to fix reobf.
> 
> > Currently I only hardcoded the path as a placeholder; I am not very well versed with Kotlin and didn't know where to place a constant containing the path (Or if any of the pre-existing constants would work)
> 
> Using a constant containing the hardcoded path is still hardcoding the path. The location of the patch file would need to be passed through the upstream data.

Hmm, in that case would the file for a fork's mappings patches (Regardless of deobfuscation or reobfuscation) preferably be fixed in the `PaperweightPatcherExtension` class (Much like dev-imports.txt is for both Paper and all forks) or manually set from the build.gradle.kts? (The same way Paper does in https://github.com/PaperMC/Paper/blob/fdef125b195f48e76fa61dfdf00fd7530e424877/build.gradle.kts#L92 for example)

**Comment by jpenilla** [comment]
Having a default value is fine, it should be configurable through the extension though.

If the file at the configured location is missing, that should also be handled so that someone not using any custom patches would not need to do any extra configuration or create any empty files.

**Comment by TheShermanTanker** [comment]
Closed PR while implementing better mappings support for Forks

**Comment by TheShermanTanker** [comment]
> 
> 
> Having a default value is fine, it should be configurable through the extension though.
> 
> If the file at the configured location is missing, that should also be handled so that someone not using any custom patches would not need to do any extra configuration or create any empty files.
> 
> Additionally this is only needed for reobf mappings, forks should not have any reason to modify the deobf mappings (unless they are trying to use completely different mappings, in which case this isn't something we plan to support officialy).

What's the userdev package for Paperweight used for? Just came back to development on reobf mappings support and I'm not sure if this is already in progress with paperweight-userdev; It would be useless for me to submit a new PR with the requested improvements if this was the case

**Pull request closed without merging**
