### PR TITLE
Add Reobf Mappings Patch Support

### PR DESCRIPTION
**Pull request by TheShermanTanker**
Second attempt to implement https://github.com/PaperMC/paperweight/pull/61

Most of the changes are only minimal, with the exception of a new task in `paperweight-lib` which isn't very elegant, and suggestions for improvements are welcome (I had a lot of trouble figuring out how to do things in Kotlin properly)

Example usage:
```
paperweight {
    serverProject.set(project(":Fork-Server"))

    usePaperUpstream(providers.gradleProperty("paperRef")) {
        additionalReobfMappingsPatch.set(layout.projectDirectory.file("build-data/reobf-mappings-patch.tiny"))
        withPaperPatcher {
            apiPatchDir.set(layout.projectDirectory.dir("patches/api"))
            apiOutputDir.set(layout.projectDirectory.dir("Fork-API"))

            serverPatchDir.set(layout.projectDirectory.dir("patches/server"))
            serverOutputDir.set(layout.projectDirectory.dir("Fork-Server"))
        }
    }
}
```

### CODE REVIEW

**Review by jpenilla — CHANGES_REQUESTED** [review]
Should either use the `PatchMappings` task or similar logic to it to properly merge the mappings, just concatenating the files isn't correct.

This also doesn't look like it handles passing the merged patch downstream in patcher, for forks of forks.

**Comment by TheShermanTanker** [comment]
> 
> 
> Should either use the `PatchMappings` task or similar logic to it to properly merge the mappings, just concatenating the files isn't correct.

I did look at PatchMappings when doing this PR, but I ultimately decided against using the logic it contained (Until I could get better confirmation) since I didn't know whether the patches would still be in the same format or not after a merge, given the output of patchMappings in `paperweight-core` for example looks vastly different from the patch format that the main Paper repo contains. Would it alter the contents of patches greatly if they were merged this way?

> 
> This also doesn't look like it handles passing the merged patch downstream in patcher, for forks of forks.

Admittedly I didn't think this was possible, but looking through the code there doesn't seem to be logic in `paperweight-patcher` that passes data downstream at all, I'm not entirely sure how this would be implemented

**Comment by kashike** [comment]
Based on https://github.com/PaperMC/paperweight-examples/issues/4#issuecomment-905103431 and discussions with the team, I'm going to close this PR at this time.

**Comment by TheShermanTanker** [comment]
If it's safe to in that case, I'll retract the previous commits I made from my Fork (I still plan on keeping the repo to track upstream development)

**Pull request closed without merging**
